# 1. Import & wrangling Data

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Set the path to the main project folder
path = r'C:\Users\luis\Desktop\Carrer Foundry boot camp\Machine Learning Specialization'

In [3]:
# Import the orders data
weather_data = pd.read_csv(os.path.join(path, 'Data Sets', 'Weather.csv'))
weather_data

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,10,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,20221028,10,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,20221029,10,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,20221030,10,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,20221031,10,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [4]:
# Import the pleasant weather data
pleasant_weather = pd.read_csv(os.path.join(path, 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))
pleasant_weather

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22946,20221028,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22947,20221029,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22948,20221030,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22949,20221031,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
pd.set_option('display.max_info_columns', 200)

In [6]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22950 entries, 0 to 22949
Data columns (total 170 columns):
 #    Column                       Non-Null Count  Dtype
---   ------                       --------------  -----
 0    DATE                         22950 non-null  int64
 1    MONTH                        22950 non-null  int64
 2    BASEL_cloud_cover            22950 non-null  int64
 3    BASEL_wind_speed             22950 non-null  float64
 4    BASEL_humidity               22950 non-null  float64
 5    BASEL_pressure               22950 non-null  float64
 6    BASEL_global_radiation       22950 non-null  float64
 7    BASEL_precipitation          22950 non-null  float64
 8    BASEL_snow_depth             22950 non-null  int64
 9    BASEL_sunshine               22950 non-null  float64
 10   BASEL_temp_mean              22950 non-null  float64
 11   BASEL_temp_min               22950 non-null  float64
 12   BASEL_temp_max               22950 non-null  float64
 13   BELGRADE_cloud_cover         22950 non-null  int64
 14   BELGRADE_humidity            22950 non-null  float64
 15   BELGRADE_pressure            22950 non-null  float64
 16   BELGRADE_global_radiation    22950 non-null  float64
 17   BELGRADE_precipitation       22950 non-null  float64
 18   BELGRADE_sunshine            22950 non-null  float64
 19   BELGRADE_temp_mean           22950 non-null  float64
 20   BELGRADE_temp_min            22950 non-null  float64
 21   BELGRADE_temp_max            22950 non-null  float64
 22   BUDAPEST_cloud_cover         22950 non-null  int64
 23   BUDAPEST_humidity            22950 non-null  float64
 24   BUDAPEST_pressure            22950 non-null  float64
 25   BUDAPEST_global_radiation    22950 non-null  float64
 26   BUDAPEST_precipitation       22950 non-null  float64
 27   BUDAPEST_sunshine            22950 non-null  float64
 28   BUDAPEST_temp_mean           22950 non-null  float64
 29   BUDAPEST_temp_min            22950 non-null  float64
 30   BUDAPEST_temp_max            22950 non-null  float64
 31   DEBILT_cloud_cover           22950 non-null  int64
 32   DEBILT_wind_speed            22950 non-null  float64
 33   DEBILT_humidity              22950 non-null  float64
 34   DEBILT_pressure              22950 non-null  float64
 35   DEBILT_global_radiation      22950 non-null  float64
 36   DEBILT_precipitation         22950 non-null  float64
 37   DEBILT_sunshine              22950 non-null  float64
 38   DEBILT_temp_mean             22950 non-null  float64
 39   DEBILT_temp_min              22950 non-null  float64
 40   DEBILT_temp_max              22950 non-null  float64
 41   DUSSELDORF_cloud_cover       22950 non-null  int64
 42   DUSSELDORF_wind_speed        22950 non-null  float64
 43   DUSSELDORF_humidity          22950 non-null  float64
 44   DUSSELDORF_pressure          22950 non-null  float64
 45   DUSSELDORF_global_radiation  22950 non-null  float64
 46   DUSSELDORF_precipitation     22950 non-null  float64
 47   DUSSELDORF_snow_depth        22950 non-null  int64
 48   DUSSELDORF_sunshine          22950 non-null  float64
 49   DUSSELDORF_temp_mean         22950 non-null  float64
 50   DUSSELDORF_temp_min          22950 non-null  float64
 51   DUSSELDORF_temp_max          22950 non-null  float64
 52   GDANSK_cloud_cover           22950 non-null  int64
 53   GDANSK_humidity              22950 non-null  float64
 54   GDANSK_precipitation         22950 non-null  float64
 55   GDANSK_snow_depth            22950 non-null  int64
 56   GDANSK_temp_mean             22950 non-null  float64
 57   GDANSK_temp_min              22950 non-null  float64
 58   GDANSK_temp_max              22950 non-null  float64
 59   HEATHROW_cloud_cover         22950 non-null  int64
 60   HEATHROW_humidity            22950 non-null  float64
 61   HEATHROW_pressure            22950 non-null  float64
 62   HEATHROW_global_radiation    22950 non-null  float64
 63   HEATHROW_precipitation       22950 non-null  float64
 64   HEATHROW_snow_depth          22950 non-null  int64
 65   HEATHROW_sunshine            22950 non-null  float64
 66   HEATHROW_temp_mean           22950 non-null  float64
 67   HEATHROW_temp_min            22950 non-null  float64
 68   HEATHROW_temp_max            22950 non-null  float64
 69   KASSEL_wind_speed            22950 non-null  float64
 70   KASSEL_humidity              22950 non-null  float64
 71   KASSEL_pressure              22950 non-null  float64
 72   KASSEL_global_radiation      22950 non-null  float64
 73   KASSEL_precipitation         22950 non-null  float64
 74   KASSEL_sunshine              22950 non-null  float64
 75   KASSEL_temp_mean             22950 non-null  float64
 76   KASSEL_temp_min              22950 non-null  float64
 77   KASSEL_temp_max              22950 non-null  float64
 78   LJUBLJANA_cloud_cover        22950 non-null  int64
 79   LJUBLJANA_wind_speed         22950 non-null  float64
 80   LJUBLJANA_humidity           22950 non-null  float64
 81   LJUBLJANA_pressure           22950 non-null  float64
 82   LJUBLJANA_global_radiation   22950 non-null  float64
 83   LJUBLJANA_precipitation      22950 non-null  float64
 84   LJUBLJANA_sunshine           22950 non-null  float64
 85   LJUBLJANA_temp_mean          22950 non-null  float64
 86   LJUBLJANA_temp_min           22950 non-null  float64
 87   LJUBLJANA_temp_max           22950 non-null  float64
 88   MAASTRICHT_cloud_cover       22950 non-null  int64
 89   MAASTRICHT_wind_speed        22950 non-null  float64
 90   MAASTRICHT_humidity          22950 non-null  float64
 91   MAASTRICHT_pressure          22950 non-null  float64
 92   MAASTRICHT_global_radiation  22950 non-null  float64
 93   MAASTRICHT_precipitation     22950 non-null  float64
 94   MAASTRICHT_sunshine          22950 non-null  float64
 95   MAASTRICHT_temp_mean         22950 non-null  float64
 96   MAASTRICHT_temp_min          22950 non-null  float64
 97   MAASTRICHT_temp_max          22950 non-null  float64
 98   MADRID_cloud_cover           22950 non-null  int64
 99   MADRID_wind_speed            22950 non-null  float64
 100  MADRID_humidity              22950 non-null  float64
 101  MADRID_pressure              22950 non-null  float64
 102  MADRID_global_radiation      22950 non-null  float64
 103  MADRID_precipitation         22950 non-null  float64
 104  MADRID_sunshine              22950 non-null  float64
 105  MADRID_temp_mean             22950 non-null  float64
 106  MADRID_temp_min              22950 non-null  float64
 107  MADRID_temp_max              22950 non-null  float64
 108  MUNCHENB_cloud_cover         22950 non-null  int64
 109  MUNCHENB_humidity            22950 non-null  float64
 110  MUNCHENB_global_radiation    22950 non-null  float64
 111  MUNCHENB_precipitation       22950 non-null  float64
 112  MUNCHENB_snow_depth          22950 non-null  int64
 113  MUNCHENB_sunshine            22950 non-null  float64
 114  MUNCHENB_temp_mean           22950 non-null  float64
 115  MUNCHENB_temp_min            22950 non-null  float64
 116  MUNCHENB_temp_max            22950 non-null  float64
 117  OSLO_cloud_cover             22950 non-null  int64
 118  OSLO_wind_speed              22950 non-null  float64
 119  OSLO_humidity                22950 non-null  float64
 120  OSLO_pressure                22950 non-null  float64
 121  OSLO_global_radiation        22950 non-null  float64
 122  OSLO_precipitation           22950 non-null  float64
 123  OSLO_snow_depth              22950 non-null  int64
 124  OSLO_sunshine                22950 non-null  float64
 125  OSLO_temp_mean               22950 non-null  float64
 126  OSLO_temp_min                22950 non-null  float64
 127  OSLO_temp_max                22950 non-null  float64
 128  ROMA_cloud_cover             22950 non-null  int64
 129  ROMA_wind_speed              22950 non-null  float64
 130  ROMA_humidity                22950 non-null  float64
 131  ROMA_pressure                22950 non-null  float64
 132  ROMA_sunshine                22950 non-null  float64
 133  ROMA_temp_mean               22950 non-null  float64
 134  SONNBLICK_cloud_cover        22950 non-null  int64
 135  SONNBLICK_wind_speed         22950 non-null  float64
 136  SONNBLICK_humidity           22950 non-null  float64
 137  SONNBLICK_pressure           22950 non-null  float64
 138  SONNBLICK_global_radiation   22950 non-null  float64
 139  SONNBLICK_precipitation      22950 non-null  float64
 140  SONNBLICK_sunshine           22950 non-null  float64
 141  SONNBLICK_temp_mean          22950 non-null  float64
 142  SONNBLICK_temp_min           22950 non-null  float64
 143  SONNBLICK_temp_max           22950 non-null  float64
 144  STOCKHOLM_cloud_cover        22950 non-null  int64
 145  STOCKHOLM_pressure           22950 non-null  float64
 146  STOCKHOLM_global_radiation   22950 non-null  float64
 147  STOCKHOLM_precipitation      22950 non-null  float64
 148  STOCKHOLM_sunshine           22950 non-null  float64
 149  STOCKHOLM_temp_mean          22950 non-null  float64
 150  STOCKHOLM_temp_min           22950 non-null  float64
 151  STOCKHOLM_temp_max           22950 non-null  float64
 152  TOURS_wind_speed             22950 non-null  float64
 153  TOURS_humidity               22950 non-null  float64
 154  TOURS_pressure               22950 non-null  float64
 155  TOURS_global_radiation       22950 non-null  float64
 156  TOURS_precipitation          22950 non-null  float64
 157  TOURS_temp_mean              22950 non-null  float64
 158  TOURS_temp_min               22950 non-null  float64
 159  TOURS_temp_max               22950 non-null  float64
 160  VALENTIA_cloud_cover         22950 non-null  int64
 161  VALENTIA_humidity            22950 non-null  float64
 162  VALENTIA_pressure            22950 non-null  float64
 163  VALENTIA_global_radiation    22950 non-null  float64
 164  VALENTIA_precipitation       22950 non-null  float64
 165  VALENTIA_snow_depth          22950 non-null  int64
 166  VALENTIA_sunshine            22950 non-null  float64
 167  VALENTIA_temp_mean           22950 non-null  float64
 168  VALENTIA_temp_min            22950 non-null  float64
 169  VALENTIA_temp_max            22950 non-null  float64
dtypes: float64(145), int64(25)
memory usage: 29.8 MB

In [7]:
pleasant_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22950 entries, 0 to 22949
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         22950 non-null  int64
 1   BASEL_pleasant_weather       22950 non-null  int64
 2   BELGRADE_pleasant_weather    22950 non-null  int64
 3   BUDAPEST_pleasant_weather    22950 non-null  int64
 4   DEBILT_pleasant_weather      22950 non-null  int64
 5   DUSSELDORF_pleasant_weather  22950 non-null  int64
 6   HEATHROW_pleasant_weather    22950 non-null  int64
 7   KASSEL_pleasant_weather      22950 non-null  int64
 8   LJUBLJANA_pleasant_weather   22950 non-null  int64
 9   MAASTRICHT_pleasant_weather  22950 non-null  int64
 10  MADRID_pleasant_weather      22950 non-null  int64
 11  MUNCHENB_pleasant_weather    22950 non-null  int64
 12  OSLO_pleasant_weather        22950 non-null  int64
 13  SONNBLICK_pleasant_weather   22950 non-null  int64
 14  STOCKHOLM_pleasant_weather   22950 non-null  int64
 15  VALENTIA_pleasant_weather    22950 non-null  int64
dtypes: int64(16)
memory usage: 2.8 MB

In [8]:
# List of cities to be removed
cities_to_remove = ['GDANSK', 'ROMA', 'TOURS']

# Filter out columns that contain the names of the cities to remove
columns_to_keep = [col for col in weather_data.columns if not any(city in col for city in cities_to_remove)]

# Create a new dataframe with the filtered columns
weather_data_filtered = weather_data[columns_to_keep]

# Check the shape to ensure the columns were removed
print(f"Shape of weather_data_filtered: {weather_data_filtered.shape}")

Shape of weather_data_filtered: (22950, 149)

In [9]:
# List of observations to be removed
observations_to_remove = ['wind_speed', 'snow_depth']

# Filter out columns that contain the names of the observations to remove
columns_to_keep = [col for col in weather_data_filtered.columns if not any(obs in col for obs in observations_to_remove)]

# Create a new dataframe with the filtered columns
weather_data_cleaned = weather_data_filtered[columns_to_keep]

# Check the shape to ensure the columns were removed
print(f"Shape of weather_data_cleaned: {weather_data_cleaned.shape}")

Shape of weather_data_cleaned: (22950, 134)

In [10]:
# Add new columns to weather_data_cleaned and copy values from nearby stations

# Copy cloud_cover, pressure, and humidity from Ljubljana to Kassel
weather_data_cleaned['KASSEL_cloud_cover'] = weather_data_cleaned['LJUBLJANA_cloud_cover']
weather_data_cleaned['KASSEL_pressure'] = weather_data_cleaned['LJUBLJANA_pressure']
weather_data_cleaned['KASSEL_humidity'] = weather_data_cleaned['LJUBLJANA_humidity']

# Copy cloud_cover, pressure, and humidity from Munchen to Sonnblick
weather_data_cleaned['SONNBLICK_cloud_cover'] = weather_data_cleaned['MUNCHENB_cloud_cover']
weather_data_cleaned['MUNCHENB_pressure'] = weather_data_cleaned['SONNBLICK_pressure']
weather_data_cleaned['SONNBLICK_humidity'] = weather_data_cleaned['MUNCHENB_humidity']

# Copy cloud_cover, pressure, and humidity from Stockholm to Oslo
weather_data_cleaned['OSLO_cloud_cover'] = weather_data_cleaned['STOCKHOLM_cloud_cover']
weather_data_cleaned['OSLO_pressure'] = weather_data_cleaned['STOCKHOLM_pressure']
weather_data_cleaned['STOCKHOLM_humidity'] = weather_data_cleaned['OSLO_humidity']

# Confirm that the columns have been added successfully
print(weather_data_cleaned[['KASSEL_cloud_cover', 'SONNBLICK_cloud_cover', 'OSLO_cloud_cover']].head())
print(weather_data_cleaned[['KASSEL_pressure', 'SONNBLICK_pressure', 'OSLO_pressure']].head())
print(weather_data_cleaned[['KASSEL_humidity', 'SONNBLICK_humidity', 'OSLO_humidity']].head())

   KASSEL_cloud_cover  SONNBLICK_cloud_cover  OSLO_cloud_cover
0                   8                      5                 5
1                   6                      6                 5
2                   8                      6                 5
3                   6                      6                 5
4                   7                      5                 5
   KASSEL_pressure  SONNBLICK_pressure  OSLO_pressure
0           1.0173              1.0304         1.0114
1           1.0173              1.0292         1.0114
2           1.0173              1.0320         1.0114
3           1.0173              1.0443         1.0114
4           1.0173              1.0430         1.0114
   KASSEL_humidity  SONNBLICK_humidity  OSLO_humidity
0             1.00                0.67           0.98
1             0.94                0.72           0.62
2             0.96                0.91           0.69
3             0.94                0.90           0.98
4             0.94                0.85           0.96

C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['KASSEL_cloud_cover'] = weather_data_cleaned['LJUBLJANA_cloud_cover']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['KASSEL_pressure'] = weather_data_cleaned['LJUBLJANA_pressure']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['KASSEL_humidity'] = weather_data_cleaned['LJUBLJANA_humidity']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['SONNBLICK_cloud_cover'] = weather_data_cleaned['MUNCHENB_cloud_cover']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['MUNCHENB_pressure'] = weather_data_cleaned['SONNBLICK_pressure']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['SONNBLICK_humidity'] = weather_data_cleaned['MUNCHENB_humidity']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['OSLO_cloud_cover'] = weather_data_cleaned['STOCKHOLM_cloud_cover']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['OSLO_pressure'] = weather_data_cleaned['STOCKHOLM_pressure']
C:\Users\luis\AppData\Local\Temp\ipykernel_8028\2344371213.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_data_cleaned['STOCKHOLM_humidity'] = weather_data_cleaned['OSLO_humidity']

In [11]:
weather_data_cleaned

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max,KASSEL_cloud_cover,MUNCHENB_pressure,STOCKHOLM_humidity
0,19600101,1,7,0.85,1.0180,0.32,0.09,0.7,6.5,0.8,...,1.0003,0.45,0.34,4.7,8.5,6.0,10.9,8,1.0304,0.98
1,19600102,1,6,0.84,1.0180,0.36,1.05,1.1,6.1,3.3,...,1.0007,0.25,0.84,0.7,8.9,5.6,12.1,6,1.0292,0.62
2,19600103,1,8,0.90,1.0180,0.18,0.30,0.0,8.5,5.1,...,1.0096,0.17,0.08,0.1,10.5,8.1,12.9,8,1.0320,0.69
3,19600104,1,3,0.92,1.0180,0.58,0.00,4.1,6.3,3.8,...,1.0184,0.13,0.98,0.0,7.4,7.3,10.6,6,1.0443,0.98
4,19600105,1,6,0.95,1.0180,0.65,0.14,5.4,3.0,-0.7,...,1.0328,0.46,0.00,5.7,5.7,3.0,8.4,7,1.0430,0.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,20221027,10,1,0.79,1.0248,1.34,0.22,7.7,15.9,11.4,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,4,1.0263,0.98
22946,20221028,10,6,0.77,1.0244,1.34,0.22,5.4,16.7,14.3,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,1.00
22947,20221029,10,4,0.76,1.0227,1.34,0.22,6.1,16.7,13.1,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,0.85
22948,20221030,10,5,0.80,1.0212,1.34,0.22,5.8,15.4,11.6,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,0.94
22949,20221031,10,5,0.84,1.0193,1.34,0.22,3.2,13.5,9.9,...,1.0142,1.13,0.41,3.4,10.7,7.9,13.5,3,1.0263,0.97

In [12]:
# Export cleaned weather data set
weather_data_cleaned.to_csv(os.path.join(path, 'Data Sets', 'task2.3_weather_cleaned.csv'))

In [14]:
# Export cleaned weather data set
pleasant_weather.to_csv(os.path.join(path, 'Data Sets', 'task2.3_pleasant_weather_cleaned.csv'))